import DataLinefdsgfghh5456service_characteristic_logEController from '../data-line-fdsgfghh5456-service-characteristic-log-e';

var DataLinefdsgfghh5456service_characteristic_logENewController = DataLinefdsgfghh5456service_characteristic_logEController;
export default DataLinefdsgfghh5456service_characteristic_logENewController;
