import DataLinefdsgfghh5456service_orderEController from '../data-line-fdsgfghh5456-service-order-e';

var DataLinefdsgfghh5456service_orderENewController = DataLinefdsgfghh5456service_orderEController;
export default DataLinefdsgfghh5456service_orderENewController;
