import DataLinefdsgfghh5456resource_specEController from '../data-line-fdsgfghh5456-resource-spec-e';

var DataLinefdsgfghh5456resource_specENewController = DataLinefdsgfghh5456resource_specEController;
export default DataLinefdsgfghh5456resource_specENewController;
